version: '3.8'

services:
  praxis-agent-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: praxis-agent-1
    ports:
      - "8000:8000"  # HTTP API
      - "8090:8090"  # WebSocket
      - "4001:4001"  # P2P
      - "9000:9000"  # SSE
    environment:
      - AGENT_NAME=praxis-agent-1
      - AGENT_VERSION=1.0.0
      - AGENT_CONFIG=/app/configs/agent1_golden.yaml
      - HTTP_PORT=8000
      - WEBSOCKET_PORT=8090
      - P2P_PORT=4001
      - SSE_PORT=9000
      - MCP_ENABLED=true
      - P2P_ENABLED=true
      - MDNS_ENABLED=true
      - LOG_LEVEL=debug
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./shared:/app/shared
      - ./configs:/app/configs
      - /var/run/docker.sock:/var/run/docker.sock  # Docker socket for Dagger
    networks:
      - praxis-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  praxis-agent-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: praxis-agent-2
    ports:
      - "8001:8001"  # HTTP API
      - "8091:8091"  # WebSocket
      - "4002:4002"  # P2P
      - "9001:9001"  # SSE
    environment:
      - AGENT_NAME=praxis-agent-2
      - AGENT_VERSION=1.0.0
      - AGENT_CONFIG=/app/configs/agent2_golden.yaml
      - HTTP_PORT=8001
      - WEBSOCKET_PORT=8091
      - P2P_PORT=4002
      - SSE_PORT=9001
      - MCP_ENABLED=true
      - P2P_ENABLED=true
      - MDNS_ENABLED=true
      - LOG_LEVEL=debug
    volumes:
      - ./shared:/app/shared
      - ./configs:/app/configs
    networks:
      - praxis-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      praxis-agent-1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  praxis-network:
    driver: bridge