agent:
  name: "praxis-agent-from-yaml"
  version: "1.0.0"
  description: "Praxis P2P Agent with Event-Driven Architecture"
  url: "http://localhost:8000"

p2p:
  enabled: true
  port: 4001
  secure: true
  rendezvous: "praxis-agents"
  enable_mdns: true
  enable_dht: true
  bootstrap_nodes: []

http:
  enabled: true
  port: 8000
  host: "0.0.0.0"

mcp:
  enabled: true
  servers: []
  limits:
    max_concurrent_requests: 100
    request_timeout_ms: 30000
    max_response_size_bytes: 10485760
    max_servers_per_node: 10
    connection_pool_size: 5
    retry_attempts: 3
    retry_backoff_ms: 1000
  log_level: "info"

llm:
  enabled: true
  provider: "openai"
  api_key: "${OPENAI_API_KEY}"
  model: "gpt-4o-mini"
  max_tokens: 4096
  temperature: 0.1
  timeout: "30s"
  function_calling:
    strict_mode: true
    max_parallel_calls: 5
    tool_timeout: "15s"
  caching:
    enabled: true
    ttl: "300s"
    max_size: 1000
  rate_limiting:
    requests_per_minute: 60
    tokens_per_minute: 100000

logging:
  level: "info"
  format: "text"
  file: ""